autobib/autobib

- src/logger.rs
- src/main.rs
Changes:
1.  `suggest!` now respect the log level, and does not display if verbosity is error or higher.
2. Do not print format codes if output is not a tty.
3. Using `eprintln!` for non-output (e.g. for prompt confirmation)
> Fix `suggest!` macro

- src/cite_search/aux.rs
- src/cite_search/tex.rs
- src/error.rs
- src/error/record.rs
- src/main.rs
- src/record/key.rs
- tests/cli.rs
As discussed offline, there are some shortcomings with the current implementation:
> Various fixes for issues involving citation keys and aliases

- src/db.rs
- src/db/validate.rs
- src/error.rs
- src/error/database.rs
- src/main.rs
- tests/cli.rs
> Improve database consistency checks

- README.md
- src/error/provider.rs
- src/main.rs
- src/provider/local.rs
- src/record/key.rs
- tests/cli.rs
`autobib update` is not meant to be run on local records, but the current error messages are confusing. For example, if `local:foo` is in the database and `local:bar` isn't, then the current behaviour is the following.
```
$ autobib update local:foo
error: Provider error: Undefined local record: foo
$ autobib update local:bar
error: Record corresponding to 'local:bar' does not exist in database
suggestion: Use `autobib get` to retrieve record
```
Tasks:
> Fix `autobib update` behaviour for local records

- Cargo.toml
Adds a release profile to `Cargo.toml`. I've added `lto = true`, as suggested for instance [here](https://matklad.github.io/2021/07/09/inline-in-rust.html#Inlining-in-Practice).
It increases release build compile times a decent amount, but the resulting binary is about 30% smaller. We should definitely use benchmarks to actually decide if it also makes things faster!
@wupr Anything else you think should be added here?
> Add release profile to `Cargo.toml`

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/db/data.rs
- src/main.rs
- src/normalize.rs
- src/record.rs
- tests/cli.rs
- tests/resources/config/extra.toml
- tests/resources/config/malformed.toml
- tests/resources/edit/stdout.txt
- tests/resources/edit/stdout_unedited.txt
- tests/resources/on_insert/config.toml
- tests/resources/on_insert/stdout.txt
When complete, this PR will resolve #90 .
The main new mechanism is that `RecordData` now implements a few methods which 'canonicalize' the record in some way:
- Whitespace normalization: replace any blocks of unescaped whitespace with a single ASCII space.
- Eprint normalization: this is more a feature for myself, but one of the ways that I (ab)use biblatex is to use biblatex eprint rendering hooks to add automatic links to biblatex entries. This change allows setting the `eprint` and `eprinttype` fields from a given biblatex field (e.g. `arxiv = {...}` becomes `eprint = {...}, eprinttype = {arxiv}`).
Certainly we could apply more renormalizations (key renaming, substituting unicode for tex-style escapes, ...?) but these are the ones that I care about the most for the moment.
In order to …
> Implementation of headless options for `autobib edit`

- src/db/state.rs
- src/logger.rs
- src/main.rs
- tests/cli.rs
This simplifies the argument structure of subcommands.
The new global flag
- replaces the `--non-interactive` flag for `autobib edit`;
- replaces the `--no-edit` flag for `autobib local`;
- implies `--prefer-current` for `autobib update`; and
- implies `--force` for `autobib delete`.
Originally proposed in a [comment](https://github.com/autobib/autobib/pull/121#issuecomment-2494960897) on #121.
> Add `--non-interactive` global flag

- Cargo.lock
- Cargo.toml
- src/db.rs
- src/db/state/null.rs
- src/db/state/record.rs
- src/entry.rs
- src/main.rs
I made quite substantial API changes upstream in [nucleo-picker](https://github.com/autobib/nucleo-picker) over the weekend. (I don't want to look at screen layout computations for a least a month, I wrote almost 1k LOC to implement single-pass multi-line terminal item rendering...)
The upstream rendering is now way better, and the API is more robust / easier to implement.
Anyway I've just made the correct changes to work with the new API but otherwise didn't modify anything else.
> Migrate to `nucleo-picker` v0.6

- Cargo.lock
- Cargo.toml
Just bumping the version since in `0.6.x` for some `x > 0` I fixed a bug where the interactive checks were done on STDOUT even though rendering is done on STDERR; this is critical to allow sub-shells e.g.
```fish
autobib edit (autobib find -f author,title)
```
since STDOUT is redirected
> Bump nucleo picker version

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/path_hash.rs
- src/record/key.rs
- tests/cli.rs
- tests/resources/path/attachment.txt
A place to work on the `autobib path` features.
Checklist:
> Implement `autobib path`

- src/db/data.rs
- src/db/sql.rs
- src/db/sql/redirect_citation_key.sql
- src/db/state/record.rs
- src/main.rs
- tests/cli.rs
- tests/resources/merge/stdout.txt
Implements record merging using the same merge logic as `autobib update`.
This defines a new command `autobib merge`. The first argument is the 'merge target', and the remaining arguments are citation keys that should be merged into the provided record. The CLI options are the same as for `autobib update` with the same merge logic.
The provided citation keys should already be in the database (i.e. no automatic retrieval here). The merge logic is essentially to sequentially merge pairs from left to right, with internal de-duplication (i.e. only joins the data for distinct records).
> Implement record merging

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/app/cli.rs
- src/app/path.rs
- src/app/picker.rs
- src/config/default_config.toml
- src/db.rs
- src/db/data.rs
- src/normalize.rs
- tests/cli.rs
- tests/resources/strip_journal_series/config.toml
- tests/resources/strip_journal_series/stdout.txt
This method adds a `--with-attachment` flag to `autobib find` to only list items which actually have at least one attachment.
I also moved the 'entry type' printing under a flag (I think it is a bit more natural to not include it by default).
In the future, once `nucleo_picker` merges the 'multiple columns' (https://github.com/autobib/nucleo-picker/issues/1) feature we can actually add the ability to also match against the attachment name, too. But for now I guess this is the next best thing and works for the use-cases that I care about, at least (e.g. "I want the PDF for that paper").
I modified the printed value upon selection with the `--with-attachment` flag to instead print a (list of) attachment paths, since this felt like the most canonical thing to do. However I do not know if …
> Add `--attachments` mode to `autobib find`

- docs/changelog/v0.3.0.md
- src/app.rs
- src/app/cli.rs
- src/db/data.rs
- src/normalize.rs
Improves `autobib edit`:
1. Adds the new normalization to `autobib edit` (now with a more robust implementation)
2. Only update the record / changelog if the normalization actually results in a change
3. Allows passing multiple keys, which is particularly useful when applying normalizations in bulk
> Improve autobib edit with new normalizations and allow multiple keys

- src/app.rs
- src/app/cli.rs
- src/db.rs
- src/db/sql.rs
- src/db/sql/clear_null_records.sql
- src/db/sql/clear_null_records_before.sql
- tests/cli.rs
Refactor the `autobib util evict` method to only allow deletion of records by age. Moreover, change the argument to be a `max-age` parameter, which is the maximum allowed age (in seconds). This is much more easier than trying to pass a timestamp!
> Only allow deletion of null records by age

- ARCHITECTURE.md
- Cargo.lock
- Cargo.toml
- docs/changelog/v0.2.0.md
- docs/changelog/v0.3.0.md
- src/app.rs
- src/db.rs
- src/db/migrate.rs
This PR cuts a new release `v0.3.0`.
We haven't implemented automated builds / testing on other platforms which was one of my `0.3.0` wish-list items, but at this point I feel a `0.3.0` release is long-awaited so I will advocate cutting one now.
@wupr Can you think of any good reasons to delay?
> New version

- src/app/edit.rs
- src/app/retrieve.rs
- src/logger.rs
- src/main.rs
Provides a detailed error debug print for errors which did not originate in the library when run with `trace`-level debugging enabled (i.e. `-vvv`).
> Augment trace logging with detailed error debug printing

- docs/changelog/next.md
- src/app/cli.rs
Makes `-I/--no-interactive` non-global, to align with `--config` and `--database`. Is there a reason that this was a global flag before?
> Remove global option from `--no-interactive`

- src/provider/mr.rs
- tests/resources/import/stdout_remote.txt
- tests/resources/import/stdout_retrieve.txt
Adds 0-padding normalization for mathscinet identifiers (which can sometimes be shorter).
> Add mr normalization with 0-padding

- src/provider/zbmath/response.rs
Correctly captures editors when using the `zbmath:` provider and friends.
> Capture editors in zbmath provider

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .markdownlint.yaml
- ARCHITECTURE.md
- README.md
- RELEASE.md
- docs/changelog/v0.2.0.md
- docs/changelog/v0.3.0.md
- docs/changelog/v0.4.0.md
- docs/changelog/v0.4.1.md
- scripts/README.md
- tests/README.md
See https://github.com/DavidAnson/markdownlint for rule definitions and configuration schema. See https://github.com/DavidAnson/markdownlint-cli2 for the command line tool that corresponds to the GitHub Action used.
When fixing existing lint errors, I disabled two rules in `.markdownlint.yaml` and made an ad-hoc exception in `README.md:291`. I didn't go through the entire list of lints and check if there were anything else to disable.
> Run Markdown lints in CI

- Cargo.lock
- Cargo.toml
- docs/changelog/next.md
- src/app.rs
- src/app/cli.rs
- src/app/path.rs
- src/config/default_config.toml
- src/http.rs
- src/main.rs
- src/provider/isbn.rs
- src/provider/jfm.rs
- src/provider/mr.rs
- src/provider/ol.rs
- src/provider/zbl.rs
- src/provider/zbmath.rs
This PR adds support for URLs when using `autobib attach`. Now you can run things like
```
autobib attach arxiv:2309.00092 https://arxiv.org/pdf/2309.00092.pdf
```
In order to distinguish between URLs and paths, I have added a mandatory check for the URI scheme (i.e. `<scheme>://`). Otherwise things like `arxiv.org/pdf/2309.00092.pdf` could equivalently be a URL or a path. I felt this was cleaner than requiring an explicit `--url` flag.
The next step is to allow the URL to be optional, if it can be determined from the identifier.
I can see two ways. First, the fully automatic way:
1. Given a call to `autobib attach <id>`, find all of the remote ids which are equivalent to `<id>`.
2. Iterate over the remote ids, in order of `preferred provider`.
3. The first such provider which supports …
> Add support for URLs when specifying attachments
